export const emojis = [
  { emoji: '😀', description: 'grinning face' },
  { emoji: '😃', description: 'grinning face with big eyes' },
  { emoji: '😄', description: 'grinning face with smiling eyes' },
  { emoji: '😁', description: 'beaming face with smiling eyes' },
  { emoji: '😆', description: 'grinning squinting face' },
  { emoji: '😅', description: 'grinning face with sweat' },
  { emoji: '🤣', description: 'rolling on the floor laughing' },
  { emoji: '😂', description: 'face with tears of joy' },
  { emoji: '🙂', description: 'slightly smiling face' },
  { emoji: '🙃', description: 'upside-down face' },
  { emoji: '🫠', description: 'melting face' },
  { emoji: '😉', description: 'winking face' },
  { emoji: '😊', description: 'smiling face with smiling eyes' },
  { emoji: '😇', description: 'smiling face with halo' },
  { emoji: '🥰', description: 'smiling face with hearts' },
  { emoji: '😍', description: 'smiling face with heart-eyes' },
  { emoji: '🤩', description: 'star-struck' },
  { emoji: '😘', description: 'face blowing a kiss' },
  { emoji: '😗', description: 'kissing face' },
  { emoji: '😚', description: 'kissing face with closed eyes' },
  { emoji: '😙', description: 'kissing face with smiling eyes' },
  { emoji: '🥲', description: 'smiling face with tear' },
  { emoji: '😋', description: 'face savoring food' },
  { emoji: '😛', description: 'face with tongue' },
  { emoji: '😜', description: 'winking face with tongue' },
  { emoji: '🤪', description: 'zany face' },
  { emoji: '😝', description: 'squinting face with tongue' },
  { emoji: '🤑', description: 'money-mouth face' },
  { emoji: '🤗', description: 'smiling face with open hands' },
  { emoji: '🤭', description: 'face with hand over mouth' },
  { emoji: '🫢', description: 'face with open eyes and hand over mouth' },
  { emoji: '🫣', description: 'face with peeking eye' },
  { emoji: '🤫', description: 'shushing face' },
  { emoji: '🤔', description: 'thinking face' },
  { emoji: '🫡', description: 'saluting face' },
  { emoji: '🤐', description: 'zipper-mouth face' },
  { emoji: '🤨', description: 'face with raised eyebrow' },
  { emoji: '😐', description: 'neutral face' },
  { emoji: '😑', description: 'expressionless face' },
  { emoji: '😶', description: 'face without mouth' },
  { emoji: '😏', description: 'smirking face' },
  { emoji: '😒', description: 'unamused face' },
  { emoji: '🙄', description: 'face with rolling eyes' },
  { emoji: '😬', description: 'grimacing face' },
  { emoji: '😮‍💨', description: 'face exhaling' },
  { emoji: '😌', description: 'relieved face' },
  { emoji: '😔', description: 'pensive face' },
  { emoji: '😪', description: 'sleepy face' },
  { emoji: '🤤', description: 'drooling face' },
  { emoji: '😵', description: 'face with crossed-out eyes' },
  { emoji: '😵‍💫', description: 'face with spiral eyes' },
  { emoji: '🤯', description: 'exploding head' },
  { emoji: '🤠', description: 'cowboy hat face' },
  { emoji: '🥳', description: 'partying face' },
  { emoji: '🥸', description: 'disguised face' },
  { emoji: '😎', description: 'smiling face with sunglasses' },
  { emoji: '🤓', description: 'nerd face' },
  { emoji: '🧐', description: 'face with monocle' },
  { emoji: '😕', description: 'confused face' },
  { emoji: '🫤', description: 'face with diagonal mouth' },
  { emoji: '😟', description: 'worried face' },
  { emoji: '🙁', description: 'slightly frowning face' },
  { emoji: '😮', description: 'face with open mouth' },
  { emoji: '😯', description: 'hushed face' },
  { emoji: '😲', description: 'astonished face' },
  { emoji: '😳', description: 'flushed face' },
  { emoji: '🥺', description: 'pleading face' },
  { emoji: '🥹', description: 'face holding back tears' },
  { emoji: '😦', description: 'frowning face with open mouth' },
  { emoji: '😧', description: 'anguished face' },
  { emoji: '😨', description: 'fearful face' },
  { emoji: '😰', description: 'anxious face with sweat' },
  { emoji: '😥', description: 'sad but relieved face' },
  { emoji: '😢', description: 'crying face' },
  { emoji: '😭', description: 'loudly crying face' },
  { emoji: '😱', description: 'face screaming in fear' },
  { emoji: '😖', description: 'confounded face' },
  { emoji: '😣', description: 'persevering face' },
  { emoji: '😞', description: 'disappointed face' },
  { emoji: '😓', description: 'downcast face with sweat' },
  { emoji: '😩', description: 'weary face' },
  { emoji: '😫', description: 'tired face' },
  { emoji: '🥱', description: 'yawning face' },
  { emoji: '😤', description: 'face with steam from nose' },
  { emoji: '😡', description: 'enraged face' },
  { emoji: '😠', description: 'angry face' },
  { emoji: '🤬', description: 'face with symbols on mouth' },
  { emoji: '🚨', description: 'urgent, police red light' },
  { emoji: '💩', description: 'pile of poo' },
  { emoji: '🤡', description: 'clown face' },
  { emoji: '💌', description: 'love letter' },
  { emoji: '💖', description: 'sparkling heart' },
  { emoji: '💥', description: 'collision' },
  { emoji: '💬', description: 'speech balloon' },
  { emoji: '🫵', description: 'index pointing at the viewer' },
  { emoji: '👍', description: 'thumbs up' },
  { emoji: '👎', description: 'thumbs down' },
  { emoji: '🤝', description: 'handshake' },
  { emoji: '👀', description: 'eyes' },
  { emoji: '👁️', description: 'eye' },
  { emoji: '👅', description: 'tongue' },
  { emoji: '🙋‍♂️', description: 'man raising hand' },
  { emoji: '🙋‍♀️', description: 'woman raising hand' },
  { emoji: '🗣️', description: 'speaking head' },
  { emoji: '🌻', description: 'sunflower' },
  { emoji: '🌿', description: 'herb' },
  { emoji: '🏖️', description: 'beach with umbrella' },
  { emoji: '🪐', description: 'ringed planet' },
  { emoji: '⭐', description: 'star' },
  { emoji: '🌈', description: 'rainbow' },
  { emoji: '💾', description: 'floppy disk' },
  { emoji: '📸', description: 'camera with flash' },
  { emoji: '📖', description: 'open book' },
  { emoji: '💰', description: 'money bag' },
  { emoji: '💵', description: 'dollar banknote' },
  { emoji: '💳', description: 'credit card' },
  { emoji: '🧾', description: 'receipt' },
  { emoji: '💹', description: 'chart increasing with yen' },
  { emoji: '📨', description: 'incoming envelope' },
  { emoji: '📦', description: 'package' },
  { emoji: '📪', description: 'closed mailbox with lowered flag' },
  { emoji: '📬', description: 'open mailbox with raised flag' },
  { emoji: '🧪', description: 'test tube' },
  { emoji: '❌', description: 'cross mark' },
  { emoji: '❎', description: 'cross mark button' },
  { emoji: '🅰️', description: 'A button (blood type)' },
  { emoji: '🆎', description: 'AB button (blood type)' },
  { emoji: '🅱️', description: 'B button (blood type)' },
  { emoji: '🆑', description: 'CL button' },
  { emoji: '🆒', description: 'COOL button' },
  { emoji: '🆓', description: 'FREE button' },
  { emoji: 'ℹ️', description: 'information' },
  { emoji: '🆔', description: 'ID button' },
  { emoji: 'Ⓜ️', description: 'circled M' },
  { emoji: '🆕', description: 'NEW button' },
  { emoji: '🅾️', description: 'O button (blood type)' },
  { emoji: '🆗', description: 'OK button' },
  { emoji: '🅿️', description: 'P button' },
  { emoji: '🆘', description: 'SOS button' },
  { emoji: '🆙', description: 'UP! button' },
  { emoji: '🆚', description: 'VS button' },
  { emoji: '🔴', description: 'red circle' },
  { emoji: '🟠', description: 'orange circle' },
  { emoji: '🟡', description: 'yellow circle' },
  { emoji: '🟢', description: 'green circle' },
  { emoji: '🔵', description: 'blue circle' },
  { emoji: '🟣', description: 'purple circle' },
  { emoji: '🟤', description: 'brown circle' },
  { emoji: '⚫', description: 'black circle' },
  { emoji: '⚪', description: 'white circle' },
  { emoji: '🟥', description: 'red square' },
  { emoji: '🟧', description: 'orange square' },
  { emoji: '🟨', description: 'yellow square' },
  { emoji: '🟩', description: 'green square' },
  { emoji: '🟦', description: 'blue square' },
  { emoji: '🟪', description: 'purple square' },
  { emoji: '🟫', description: 'brown square' },
  { emoji: '⬛', description: 'black large square' },
  { emoji: '⬜', description: 'white large square' },
]
